name: CI Checks

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_BUCKET_NAME: ${{ vars.TF_VAR_BUCKET_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Lint Code
        run: devbox run lint

      - name: New Cloudspace
        run: devbox run new-cloudspace

      - name: Initialize Cloudspace Terraform workspace
        run: devbox run init
      
      - name: Plan Cloudspace Terraform changes
        run: devbox run plan-cloudspace
        env:
          RXTSPOT_TOKEN: ${{ secrets.RXTSPOT_TOKEN }}