name: Apply Terraform Code Changes

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write     # This is required for requesting the JWT
  contents: read      # This is required for actions/checkout
  pull-requests: write # This is required for commenting on PRs

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  tf-fmt-checks:
    name: Terraform Format Checks
    runs-on: ubuntu-latest
    steps:
      - name: Run Terraform Format Check
        uses: estenrye/tf-fmt-composite-action@v1.0.18

  tf-lint-checks:
    name: Tflint Checks on Terraform Code
    runs-on: ubuntu-latest
    steps:
      - name: Run Terraform Linting Rules
        uses: estenrye/tf-lint-composite-action@v1.0.0
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}

  tf-sec-checks:
    name: Tfsec Checks on Terraform Code
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name : Check out Git Repository
        uses: actions/checkout@v4

      # Tfsec - Security scanner for your Terraform code
      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          additional_args: --ignore-hcl-errors
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}

  tf-checkov-checks:
    name: Checkov Checks on Terraform Code
    runs-on: ubuntu-latest

    steps:
      # Checkout Repository
      - name : Check out Git Repository
        uses: actions/checkout@v4

      # Checkov - Static code analysis tool for infrastructure-as-code
      - name: Run Checkov
        run: |
           docker run -t -v ${{ github.workspace }}:/tf --workdir /tf bridgecrew/checkov --directory /tf --skip-check CKV2_GHA_1

  tf-apply:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest
    needs: [tf-fmt-checks, tf-lint-checks, tf-sec-checks, tf-checkov-checks]
    env:
      TF_VAR_GITHUB_ADMIN_TOKEN: ${{ secrets.TF_VAR_GITHUB_ADMIN_TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=bucket=${{vars.TF_VAR_BUCKET_NAME}}
        working-directory: backend-aws-s3

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: backend-aws-s3

      - name: Run Terraform Plan
        run: terraform plan -out .planfile
        working-directory: backend-aws-s3

      - name: Apply Terraform Plan
        run: terraform apply -auto-approve .planfile
        working-directory: backend-aws-s3
